<a href="https://colab.research.google.com/github/Leandro-Bezerra-de-Carvalho/base-alunos-GENERATION-/blob/main/tratamento_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/ChiaviniK/dados.git

Cloning into 'dados'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 31 (delta 10), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (31/31), 9.43 KiB | 9.43 MiB/s, done.
Resolving deltas: 100% (10/10), done.

In [ ]:
import pandas as pd

vendas = '/content/dados/vendas.csv'
clientes = '/content/dados/clientes.csv'
dados = '/content/dados/dados.csv'
produto = '/content/dados/produtos.csv'

df_vendas= pd.read_csv(vendas)
df_clientes = pd.read_csv(clientes)

# MERGE THE VENDAS AND CLIENTES
df_vendas_clientes = pd.merge(df_vendas, df_clientes,
                              left_on='Cliente',
                              right_on= 'Id Cliente',
                              how = 'inner')

display(df_vendas_clientes)

,Id venda,Produto,Quantidade,Cliente,Id Cliente,Nome,CPF
0,1,Bolacha,2,1,1,João Silva,12345678901
1,2,Refrigerante,1,2,2,Maria Souza,98765432109
2,3,Chocolate,3,3,3,Carlos Ferreira,45678912345
3,4,Pizza,2,4,4,Ana Santos,56789012345
4,5,Café,1,5,5,Pedro Oliveira,90876543210
5,6,Sanduíche,2,6,6,Luciana Alves,23456789012
6,7,Suco,3,7,7,Ricardo Pereira,34567890123
7,8,Bolo,1,8,8,Fernanda Costa,67890123456
8,9,Água,2,9,9,Gabriel Rodrigues,90123456789
9,10,Pão de Queijo,1,10,10,Isabela Martins,43210987654
10,11,Sorvete,3,11,11,André Almeida,54321098765
11,12,Chips,2,12,12,Daniela Lima,78901234567
12,13,Barrinha de Cereal,1,13,13,Paulo Cardoso,89012345678
13,14,Salgadinho,2,14,14,Sandra Santos,21098765432
14,15,Maçã,3,15,15,Roberto Castro,65432109876

In [ ]:
#DESAFIO -> QUANTO O CLIENTE GASTOU EM COMPRA

# Descobrir onde estar o valor do produto
df_produtos = pd.read_csv(produto)

# mesclar tabela df_vendas_clientes com a tabela que tem o valor
df_vendas_produtos = pd.merge(df_vendas_clientes, df_produtos,
                              left_on = 'Produto',
                              right_on= 'Produto',
                              how = 'inner')

# criar novo campo, para mostrar o total gasto na compra

df_vendas_produtos['Total Gasto'] = (df_vendas_produtos['Valor'] * df_vendas_produtos['Quantidade'])

# Display
display(df_vendas_produtos)

,Id venda,Produto,Quantidade,Cliente,Id Cliente,Nome,CPF,Valor,Tipo,Total Gasto
0,1,Bolacha,2,1,1,João Silva,12345678901,2.5,Alimento,5.0
1,2,Refrigerante,1,2,2,Maria Souza,98765432109,5.0,Bebida,5.0
2,3,Chocolate,3,3,3,Carlos Ferreira,45678912345,3.0,Doce,9.0
3,4,Pizza,2,4,4,Ana Santos,56789012345,8.0,Alimento,16.0
4,5,Café,1,5,5,Pedro Oliveira,90876543210,2.0,Bebida,2.0
5,6,Sanduíche,2,6,6,Luciana Alves,23456789012,6.5,Alimento,13.0
6,7,Suco,3,7,7,Ricardo Pereira,34567890123,3.5,Bebida,10.5
7,8,Bolo,1,8,8,Fernanda Costa,67890123456,4.5,Doce,4.5
8,9,Água,2,9,9,Gabriel Rodrigues,90123456789,1.5,Bebida,3.0
9,10,Pão de Queijo,1,10,10,Isabela Martins,43210987654,2.5,Snack,2.5
10,11,Sorvete,3,11,11,André Almeida,54321098765,5.5,Doce,16.5
11,12,Chips,2,12,12,Daniela Lima,78901234567,3.0,Snack,6.0
12,13,Barrinha de Cereal,1,13,13,Paulo Cardoso,89012345678,2.0,Alimento,2.0
13,14,Salgadinho,2,14,14,Sandra Santos,21098765432,4.0,Snack,8.0
14,15,Maçã,3,15,15,Roberto Castro,65432109876,1.0,Fruta,3.0